Main_RankUp/RankUp/Models/BoardUsers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RankUp.Models
{
    public class BoardUsers
    {
        [Required]
        public int id { get; set; }
        [Required]
        public User user { get; set; }
        [Required]
        public int CVsReviewed { get; set; }
        [Required]
        public bool isAdmin { get; set; }
        [Required]
        public bool isAvailable { get; set; } 
    }
}

Main_RankUp/RankUp/Controllers/BoardUsersController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RankUp.Models;
using RankUp.ViewModels;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace RankUp.Controllers
{
    public class BoardUsersController : Controller
    {

        private IBoardUserRepository boardUserRepository;
        private IReviewRequestsRepository reviewRequestsRepository;
        private readonly ICVReview CvReview;
        private readonly IForm form;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly ITaskRepository taskRepository;
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> siginManager;
        private readonly IUserRepository userRepository;
        private readonly IStatisticalDataRepository statisticalDataRepository;

        public BoardUsersController(ICVReview cVReview, IBoardUserRepository boardUser, IForm form,
            IReviewRequestsRepository reviewRequestsRepository, IWebHostEnvironment webHostEnvironment,
            ITaskRepository taskRepository, UserManager<User> userManager, SignInManager<User> signInManager,
            IUserRepository userRepository, IStatisticalDataRepository statisticalDataRepository)
        {
            this.boardUserRepository = boardUser;
            this.reviewRequestsRepository = reviewRequestsRepository;
            this.CvReview = cVReview;
            this.form = form;
            this.webHostEnvironment = webHostEnvironment;
            this.taskRepository = taskRepository;
            this.userManager = userManager;
            this.siginManager = signInManager;
            this.userRepository = userRepository;
            this.statisticalDataRepository = statisticalDataRepository;
        }

        public IActionResult Index()
        {
            var userid = userManager.GetUserId(HttpContext.User);
            ViewBag.AllTasks = taskRepository.GetTasks(userid);
            ViewBag.pendingCVReview = reviewRequestsRepository.GetCVReviewCount();
            ViewBag.pendingLinkedinReview = reviewRequestsRepository.GetLinkedInReviewCount();
            ViewBag.pendingIVReview = reviewRequestsRepository.GetIVReviewCount();
            ViewBag.activeHR = boardUserRepository.GetActiveHR();
            ViewBag.activeUsersCount = reviewRequestsRepository.getActiveUsersCount();
            ViewBag.totalReviewdCVRequests = reviewRequestsRepository.GetTotalReviewdCVRequests();
            ViewBag.totalReviewdIVRequests = reviewRequestsRepository.GetTotalReviewdIVRequests();
            ViewBag.totalReviewdLinkedInRequests = reviewRequestsRepository.GetTotalReviewdLinkedInRequests();
            
            var requestsHistory = reviewRequestsRepository.GetRequestsHistory();

            // trying to create the same data structure as in chart.js file
            var chartDataSet = new List<Object>();
            Random random = new Random();
            HashSet<string> distinctColors = new HashSet<string>();

            foreach (var element in requestsHistory)
            {
                // to generate a random distinct color for each chart line,
                // save the newly generated color in a set
                string color;
                do
                {
                    //color = Color.FromArgb(0, random.Next(100, 255), random.Next(100, 255), random.Next(100, 255));
                    color = String.Format("#{0:X6}", random.Next(0x1000000)); // = "#A197B9"

                } while (distinctColors.Contains(color));

                distinctColors.Add(color);
            
                var chartLineData = new
                {
                    label = element.Key,
                    data = element.Value,
                    borderColor = color,
                    fill = false,
                    borderWidth = 2,
                };

                chartDataSet.Add(chartLineData);
            }

            ViewBag.requestsHistory = chartDataSet;


            var usersCountries = userRepository.GetUsersCountries();
            List<int> countUsers = new List<int>();
            List<string> countCountries = new List<string>();
            foreach(var element in usersCountries)
            {
                countCountries.Add(element.Item1);
                countUsers.Add(element.Item2);
            }
            ViewBag.usersCount = countUsers;
            ViewBag.countriesCount = countCountries;


            #region number of submitted requests and their percentage

            // 1)
            var submittedRequestsWithinAWeek = statisticalDataRepository.GetTotalSubmittedRequestsWithinAWeek();
            var submittedRequestsPercentage = statisticalDataRepository.GetTotalSubmittedRequestsPercentage();

            ViewBag.submittedRequestsWithinAWeek = submittedRequestsWithinAWeek;
            ViewBag.submittedRequestsPercentage = submittedRequestsPercentage;


            #endregion

            #region number of completed requests and their percentage

            var completedRequestsWithinAWeek = statisticalDataRepository.GetTotalCompletedRequestsWithinAWeek();
            var completedRequestsPercentage = statisticalDataRepository.GetTotalCompletedRequestsPercentage();

            ViewBag.completedRequestsWithinAWeek = completedRequestsWithinAWeek;
            ViewBag.completedRequestsPercentage = completedRequestsPercentage;

            #endregion

            #region user retention

            var userRetention = statisticalDataRepository.GetUserRetentionWithinAWeek();
            var userRetentionPercentage = statisticalDataRepository.GetUserRetentionPercentage();

            ViewBag.userRetention = userRetention;
            ViewBag.userRetentionPercentage = userRetentionPercentage;

            #endregion


            #region avg response time and its percentage

            var averageResponseTime = statisticalDataRepository.GetTotalAverageResponseTimeWithinAWeek();
            var averageResponseTimePercentage = statisticalDataRepository.GetTotalAverageResponseTimePercentage();

            ViewBag.avgResponseTimeWithinAWeek = averageResponseTime;
            ViewBag.avgResponseTimePercentage = averageResponseTimePercentage;

            #endregion

            // exclude el HR members 
            ViewBag.allUsersCount = userRepository.GetAllUsers().Count();

            return View();
        }
        [HttpGet]
        public IActionResult ViewBoardUsers()
        {
            ViewBag.AllBoardUsers = boardUserRepository.GetAllBoardUsers();
            return View();
        }

        [HttpGet]
        public IActionResult EditBoardUser(int boardUserId)
        {
            BoardUsers boardUser = boardUserRepository.GetBoardUserById(boardUserId);
            return View(boardUser);
        }

        [HttpPost]
        public IActionResult EditBoardUser(BoardUsers UpdatedBoardUser)
        {
            if (ModelState.IsValid)
            {
                boardUserRepository.Update(UpdatedBoardUser);

                return RedirectToAction("ViewBoardUsers");
            }

            return View(UpdatedBoardUser);
        }
    
        [HttpGet]
        public IActionResult AddNewHRMember()
        {
            return View();
        }    
        [HttpPost]
        public async Task<IActionResult> AddNewHRMember(HRMember NewBoardUser)
        {
            ViewBag.addNewHR = false;

            // Setting newBoardUser's password to default value: RankUp@1234,
            // then notify the admin with it.
            NewBoardUser.password = "RankUp@1234";

            User newUser = new User
            {
                firstName = NewBoardUser.firstName,
                lastName = NewBoardUser.lastName,
                UserName = NewBoardUser.email,
                Email = NewBoardUser.email,
                PhoneNumber = NewBoardUser.phone,
                gender = NewBoardUser.gender,
            };
            var result = await userManager.CreateAsync(newUser, NewBoardUser.password);
            if (result.Succeeded)
            {
                var token = await userManager.GenerateEmailConfirmationTokenAsync(newUser);
                var confirmationLink = Url.Action("ConfirmEmail", "Account", new { userId = newUser.Id, token = token }, Request.Scheme);
                WelcomeRequest welcomeRequest = new WelcomeRequest { link = confirmationLink, UserName = newUser.firstName, mail = newUser.Email };
                //bool mailResult = await SendWelcomeMail(welcomeRequest);

                BoardUsers boardUser = new BoardUsers
                {
                    isAdmin = NewBoardUser.isAdmin,
                    isAvailable = NewBoardUser.isAvailable,
                    user = newUser,
                    CVsReviewed = 0,

                };
                
                boardUserRepository.Add(boardUser);

                ViewBag.addNewHR = true;

                return RedirectToAction("ViewBoardUsers");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            return View();

        }
    
        [HttpGet]
        public IActionResult ViewRequests()
        {
            ViewBag.latestCV = reviewRequestsRepository.GetLatestCVRequest();
            ViewBag.latestInterview = reviewRequestsRepository.GetLatestInterviewRequest();
            ViewBag.latestLinkedIn = reviewRequestsRepository.GetLatestLinkedInRequest();
            return View();
        }

        [HttpGet]
        public IActionResult Review()
        {
            ViewBag.sections = form.GetOrderedSections();
            ViewBag.questions = form.GetOrderedQuestions();
            ViewBag.options = form.GetOrderedOptionsByQuestion();

Main_RankUp/RankUp/Views/BoardUsers/AddNewHRMember.cshtml
@model RankUp.ViewModels.HRMember

@{
    Layout = "~/Views/Shared/_navBar.cshtml";
    ViewBag.Title = "RankUp - Add New Board User";
}

<link rel="stylesheet" href="~/Content/BoardUsers/css/style.css" />


<div class="main-panel">
    <div class="content-wrapper">

        <div class="row ">
            <div class="col grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <form enctype="multipart/form-data" method="post" asp-controller="BoardUsers" asp-action="AddNewHRMember">

                            <div class="card mb-3">
                                <div class="card-body">
                                    <div class="form-group row">
                                        <div class="col-sm-3">

                                            <label asp-for='firstName' class="mb-0">First Name</label>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <input style="color:white" class="form-control" id='firstName' name="firstName" type="text">
                                            @* To display an error msg for this field*@
                                            <span asp-validation-for='firstName' class="text-danger"></span>
                                        </div>
                                    </div>

                                    <hr>

                                    <div class="form-group row">
                                        <div class="col-sm-3">
                                            <label asp-for='lastName' class="mb-0">Last Name</label>

                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <input style="color:white" class="form-control" id='lastName' name="lastName" type="text">
                                            <span asp-validation-for='lastName' class="text-danger"></span>

                                        </div>
                                    </div>

                                    <hr>

                                    <div class="form-group row">
                                        <div class="col-sm-3">
                                            <label asp-for='email' class="mb-0">Email</label>

                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <input style="color:white" class="form-control" id='email' name="email" type="email">
                                            <span asp-validation-for='email' class="text-danger"></span>

                                        </div>
                                    </div>


                                    <hr>

                                    <div class="form-group row">
                                        <div class="col-sm-3">
                                            <label asp-for='phone' class="mb-0">Phone Number</label>

                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <input style="color:white" class="form-control" id='phone' name="phone">
                                            <span asp-validation-for='phone' class="text-danger"></span>

                                        </div>
                                    </div>

                                    <hr>

                                    <div class="form-group row">
                                        <div class="col-sm-3">
                                            <label asp-for='gender' class="mb-0">Gender</label>

                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <input class="mr-3" value="M" id='gender' name="gender" type="radio" checked>Male
                                            <input class="mr-3 ml-3" value="F" id='gender' name="gender" type="radio">Female

                                            <span asp-validation-for='gender' class="text-danger"></span>

                                        </div>
                                    </div>

                                    <hr>

                                    <div class="form-group row">
                                        <div class="col-sm-3">
                                            <label asp-for='isAdmin' class="mb-0">Admin</label>

                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <input id='isAdmin' name="isAdmin" type="checkbox" checked value="True"><label class="ml-3 mr-3">Admin</label>
                                            <span asp-validation-for='isAdmin' class="text-danger"></span>

                                        </div>
                                    </div>
                                    <hr>

                                    <div class="form-group row">
                                        <div class="col-sm-3">
                                            <label asp-for='isAvailable' class="mb-0">Available</label>

                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <input id='isAdmin' name="isAvailable" type="checkbox" checked value="True"><label class="ml-3 mr-3">Available</label>

                                            <span asp-validation-for='isAvailable' class="text-danger"></span>

                                        </div>
                                    </div>

                                    <button style="float:right" type="submit" class="btn btn-success mt-3 mb-0">Add</button>
                                    @*<button style="float:right" type="submit" class="btn btn-success mt-3 mb-0" onclick="Confirm()">Add</button>*@
                                    <a style="float:left" asp-controller="BoardUsers" asp-action="ViewBoardUsers" class="btn btn-success mt-3 mb-0">Back</a>

                                </div>
                            </div>

                            @* To display all Validation Errors*@
                            <div asp-validation-summary="All" class="text-danger"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="loading-modal"><!-- Place at bottom of page --></div>


@*Confirmation msg for creating new board user and their password*@
<div id="confirmationMsgModal" class="modal">

    <div class="modal-content">
        <div class="modal-headerr" style="text-align:center">
            <span class="close" onclick="closeModal()">&times;</span>

        </div>


        <div class="modal-body">

            <h5 id="confirmationHeader" style="margin-bottom: 2rem"></h5>
        </div>

        <div style="text-align:center" class="modal-footer">
            <button style="margin-left:auto;margin-right:auto" class="btn" onclick="closeModal()">OK</button>

        </div>
    </div>
</div>



<script>

    var modal = document.getElementById("confirmationMsgModal");

    var userFirstName = document.getElementById("firstName").value;
    var userLastName = document.getElementById("lastName").value;
    var userName = userFirstName + " " + userLastName;



    function closeModal() {

        modal.style.display = "none";
    }

    function Confirm() {

        modal.style.display = "block";

        if ('@ViewBag.addNewHR' == 'True') {

            // how to let any user to change his password ??????
            document.getElementById("confirmationHeader").innerText = "New HR member " + userName + " has been created with password: RankUp@1234\nFeel free to let him change it";
        }
        else {

            document.getElementById("confirmationHeader").innerText = "Can't add New HR member: " + userName;
        }
    }

</script>

Main_RankUp/RankUp/Views/BoardUsers/EditBoardUser - bk.cshtml
@model RankUp.Models.BoardUsers

@{
    Layout = "~/Views/Shared/_navBar.cshtml";
    ViewBag.Title = "RankUp - Edit Board User";
}



<div class="main-panel">
    <div class="content-wrapper">

        <div class="row ">
            <div class="col grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <form enctype="multipart/form-data" method="post" asp-controller="BoardUsers" asp-action="EditBoardUser">


                            @Html.HiddenFor(Model => Model.id)
                            @Html.HiddenFor(Model => Model.CVsReviewed)
                            @Html.HiddenFor(Model => Model.user)
                            @Html.HiddenFor(Model => Model.user.Id)
                            @Html.HiddenFor(Model => Model.user.CV)
                            @Html.HiddenFor(Model => Model.user.PhoneNumber)
                            @Html.HiddenFor(Model => Model.user.industry)
                            @Html.HiddenFor(Model => Model.user.univeristy)
                            @Html.HiddenFor(Model => Model.user.jobStartDate)
                            @Html.HiddenFor(Model => Model.user.jobStatus)
                            @Html.HiddenFor(Model => Model.user.jobTitle)
                            @Html.HiddenFor(Model => Model.user.gender)
                            @Html.HiddenFor(Model => Model.user.Email)
                            @Html.HiddenFor(Model => Model.user.company)
                            @Html.HiddenFor(Model => Model.user.country)
                            @Html.HiddenFor(Model => Model.user.state)
                            @Html.HiddenFor(Model => Model.user.area)
                            @Html.HiddenFor(Model => Model.user.birthDate)
                            @Html.HiddenFor(Model => Model.user.AccessFailedCount)
                            @Html.HiddenFor(Model => Model.user.ConcurrencyStamp)
                            @Html.HiddenFor(Model => Model.user.EmailConfirmed)
                            @Html.HiddenFor(Model => Model.user.jobStartDate)
                            @Html.HiddenFor(Model => Model.user.LockoutEnabled)
                            @Html.HiddenFor(Model => Model.user.LockoutEnd)
                            @Html.HiddenFor(Model => Model.user.NormalizedEmail)
                            @Html.HiddenFor(Model => Model.user.NormalizedUserName)
                            @Html.HiddenFor(Model => Model.user.PasswordHash)
                            @Html.HiddenFor(Model => Model.user.PhoneNumberConfirmed)
                            @Html.HiddenFor(Model => Model.user.photo)
                            @Html.HiddenFor(Model => Model.user.SecurityStamp)
                            @Html.HiddenFor(Model => Model.user.TwoFactorEnabled)
                            @Html.HiddenFor(Model => Model.user.UserName)


                            <div class="card mb-3">
                                <div class="card-body">
                                    <div class="form-group row">
                                        <div class="col-sm-3">

                                            <label asp-for='@Model.user.firstName' class="mb-0">First Name</label>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <input class="form-control" asp-for='@Model.user.firstName' type="text" value='@Model.user.firstName'>
                                            @* To display an error msg for this field*@
                                            <span asp-validation-for='@Model.user.firstName' class="text-danger"></span>
                                        </div>
                                    </div>

                                    <hr>

                                    <div class="form-group row">
                                        <div class="col-sm-3">
                                            <label asp-for='@Model.user.lastName' class="mb-0">Last Name</label>

                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            <input class="form-control" asp-for='@Model.user.lastName' type="text" value='@Model.user.lastName'>
                                            <span asp-validation-for='@Model.user.lastName' class="text-danger"></span>

                                        </div>
                                    </div>

                                    <hr>

                                    <div class="form-group row">
                                        <div class="col-sm-3">
                                            <label asp-for='@Model.isAdmin' class="mb-0">Admin</label>

                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            @if (Model.isAdmin == true)
                                            {
                                                <input asp-for='@Model.isAdmin' type="radio" name="isAdmin" value="True" checked><label class="ml-3 mr-3">Admin</label>
                                                <input asp-for='@Model.isAdmin' type="radio" name="isAdmin" value="False"><label class="ml-3 mr-3">Not an Admin</label>

                                            }
                                            else
                                            {
                                                <input asp-for='@Model.isAdmin' type="radio" name="isAdmin" value="True"><label class="ml-3 mr-3">Admin</label>
                                                <input asp-for='@Model.isAdmin' type="radio" name="isAdmin" value="False" checked><label class="ml-3 mr-3">Not an Admin</label>

                                            }
                                            <span asp-validation-for='@Model.isAdmin' class="text-danger"></span>

                                        </div>
                                    </div>
                                    <hr>

                                    <div class="form-group row">
                                        <div class="col-sm-3">
                                            <label asp-for='@Model.isAvailable' class="mb-0">Available</label>

                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                            @if (Model.isAvailable == true)
                                            {
                                                <input asp-for='@Model.isAvailable' type="radio" name="isAvailable" value="True" checked><label class="ml-3 mr-3">Available</label>
                                                <input asp-for='@Model.isAvailable' type="radio" name="isAvailable" value="False"><label class="ml-3 mr-3">Not Available</label>

                                            }
                                            else
                                            {
                                                <input asp-for='@Model.isAvailable' type="radio" name="isAvailable" value="True"><label class="ml-3 mr-3">Available</label>
                                                <input asp-for='@Model.isAvailable' type="radio" name="isAvailable" value="False" checked><label class="ml-3 mr-3">Not Available</label>

                                            }
                                            <span asp-validation-for='@Model.isAvailable' class="text-danger"></span>

                                        </div>
                                    </div>

                                    <button style="float:right" type="submit" class="btn btn-success mt-3 mb-0">Save</button>
                                    <a style="float:left" asp-controller="BoardUsers" asp-action="ViewBoardUsers" class="btn btn-success mt-3 mb-0">Back</a>

                                </div>
                            </div>

                            @* To display all Validation Errors*@
                            <div asp-validation-summary="All" class="text-danger"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>